numero1=5
numero2=-3
numero3=6.81
numero4=5.0
numero5= "c"
numero6="ciao"
numero7=-0.5
numero8= "5"
numero9="5.0"
print(numero1,type(numero1))
print(numero2,type(numero2))
print(numero3,type(numero3))
print(numero4,type(numero4))
print(numero5,type(numero5))
print(numero6,type(numero6))
print(numero7,type(numero7))
print(numero8,type(numero8))
print(numero9,type(numero9))
numero8_int=int(numero8)
numero3_float=float(numero3)
numero4_float=float(numero4)
numero7_float=float(numero7)
nome="scuola"
data="13/11/2024"
numero="13"
numero_t="0119553131"
mail="segreteria@iismajoranamoncalieri.edu.it"
numero_int=int(numero)
numero_t_int=int(numero_t)
print(nome,type(nome))
print(data,type(data))
print(numero,type(numero))
print(numero_t,type(numero_t))
print(mail,type(mail))
numero8_float=float(numero8_int)
numero_float=float(numero_int)
numero_t_float=float(numero_t_int)
print(numero8_float,type(numero8_float))
print(numero_float,type(numero_float))
print(numero_t_float,type(numero_t_int))